qdrant:
  host: localhost
  port: 6333
  collection_name: legal_documents
  vector_size: 768

processing:
  chunk_size: 1000
  chunk_overlap: 200
  allowed_extensions: ['.pdf', '.html', '.xml' , '.txt']
  text_clean_patterns:
    - '\d{1,3}\s?-\s?ФЗ'
    - '(?m)^\s*\d+\s*$'
  legal_text:
    section_patterns:
      - type: Раздел
        pattern: 'Раздел [IVXLCDM]+\. (.*)'
      - type: Глава
        pattern: 'Глава \d+\. (.*)'
    article_threshold: 500

embeddings:
  model_name: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
  device: cpu
  batch_size: 32 